name: Conda CI
on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo secret
      run: echo ${{ secrets.TEST_SECRET }}

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        miniforge-version: latest
        use-mamba: true
        channels: conda-forge

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge fenics-dolfinx=0.7.0

    - name: Install local package and dependencies
      shell: bash -l {0}
      run: |
        pip install .[test]

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest test/ --cov festim --cov-report xml --cov-report term
    
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
      with:
        files: ./coverage.xml
        verbose: true
